sudo: false
language: 
  node_js
node_js: '8'
install:
  - npm install
  - npm install -g codecov
  - npm install -g istanbul
script:  
  - cross-env NODE_ENV=test && istanbul cover ./node_modules/mocha/bin/_mocha
  - codecov